In [3]:
import numpy as np
import scipy as sp
import scipy.linalg as sl

In [4]:
# scipy.linalg.sqrtm(A, disp=True, blocksize=64)
# a = np.matrix('1 2; 3 4')
# print(a)
# [[1 2]
#  [3 4]]
#
# np.matrix([[1, 2], [3, 4]])
# matrix([[1, 2],
# #    [3, 4]])

In [28]:
a=np.matrix('0.000061,0.00007,0.000057;0.00007,0.000105,0.000066;0.000057,0.000066,0.000148')
a

matrix([[  6.10000000e-05,   7.00000000e-05,   5.70000000e-05],
        [  7.00000000e-05,   1.05000000e-04,   6.60000000e-05],
        [  5.70000000e-05,   6.60000000e-05,   1.48000000e-04]])

In [35]:
sqr=sl.sqrtm(a)
sqr

array([[ 0.00605152,  0.00420156,  0.00259344],
       [ 0.00420156,  0.0089523 ,  0.00268389],
       [ 0.00259344,  0.00268389,  0.01157889]])

In [7]:
a=np.array([1,2,3]).reshape(1,3)

In [8]:
b=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [51]:
a.T*b

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [30]:
def dependify(st,m,x):
    return np.matmul(np.matmul(st,m),x)

In [36]:
def simulation(r_s,r_euro,sig_rus,sig_sp,sig_eurox,sig_euro_eurox,s1,s2,s3,M):
    st=np.array([s1,s2,s3]).reshape(3,1)
    process=[st]
    r=np.array([r_s,r_euro,r_euro-sig_euro_eurox]).reshape(3,1)
    for i in range(731):
        X=np.random.normal(loc=0,scale=1,size=[3,1])
        st+=r*st*1.0/20+np.matmul(st.T*M,X)
        process.append(st)
    return process

In [37]:
simulation(0.2,0.1,np.sqrt(0.000105),np.sqrt(0.000061),np.sqrt(0.000148),-0.000004,2355.54,1364.563,3495.8,m)

[array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
        [   35123.422087  ],
        [  154575.91980695]]), array([[ 3067018.85018512],
   

In [14]:
st=np.array([1,2,3]).reshape(3,1)
min(st)

array([1])

In [21]:
def final_value(threshold,principal,coupon,process):
    check = 0
    for i in process[-90,]:
        if i[0][0]<threshold or i[1][0]<threshold or i[2][0]<threshold:
            check=1
            payoff=principal*(min(i)/initial)

In [69]:
for j in st>1:
    if j == False:
        b = 1
        break

array([[False],
       [ True],
       [ True]], dtype=bool)

In [72]:
from datetime import date

In [82]:
date(2019,4,11)-date(2017,4,7)

datetime.timedelta(734)

In [22]:
for i in range()

SyntaxError: invalid syntax (<ipython-input-22-e3f9b14113c5>, line 1)

In [27]:
a=[1,2,3,4,5,6,7,8]
for i in a[-3,8]:
    print(i)

TypeError: list indices must be integers or slices, not tuple

In [38]:
a=[1,2,3,4,5]
print(a[-3:])

[3, 4, 5]
